# Generated by Django 4.1.5 on 2023-01-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="printer",
            name="api_key",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="printer",
            name="check_type",
            field=models.CharField(
                choices=[("kitchen", "kitchen"), ("client", "client")],
                default="",
                max_length=32,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="printer",
            name="point_id",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
    ]
